<?php

namespace Database\Seeders;

use App\Models\Table;
use App\Models\TableCategory;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Clear existing tables first
        Table::query()->delete();
        
        // Get categories for reference
        $regularCategory = TableCategory::where('name', 'Regular')->first();
        $vipCategory = TableCategory::where('name', 'VIP')->first();
        $coupleCategory = TableCategory::where('name', 'Couple')->first();
        $familyCategory = TableCategory::where('name', 'Family')->first();
        $groupCategory = TableCategory::where('name', 'Group')->first();
        $privateCategory = TableCategory::where('name', 'Private')->first();
        
        $tables = [
            // Regular tables (Main dining area)
            ['number' => 'T001', 'capacity' => 4, 'category_id' => $regularCategory->id, 'location' => 'Main Dining Area'],
            ['number' => 'T002', 'capacity' => 4, 'category_id' => $regularCategory->id, 'location' => 'Main Dining Area'],
            ['number' => 'T003', 'capacity' => 4, 'category_id' => $regularCategory->id, 'location' => 'Main Dining Area'],
            ['number' => 'T004', 'capacity' => 4, 'category_id' => $regularCategory->id, 'location' => 'Main Dining Area'],
            ['number' => 'T005', 'capacity' => 4, 'category_id' => $regularCategory->id, 'location' => 'Main Dining Area'],
            
            // Couple tables (Romantic section)
            ['number' => 'C001', 'capacity' => 2, 'category_id' => $coupleCategory->id, 'location' => 'Romantic Corner'],
            ['number' => 'C002', 'capacity' => 2, 'category_id' => $coupleCategory->id, 'location' => 'Romantic Corner'],
            ['number' => 'C003', 'capacity' => 2, 'category_id' => $coupleCategory->id, 'location' => 'Window Side'],
            
            // Family tables (Family section)
            ['number' => 'F001', 'capacity' => 6, 'category_id' => $familyCategory->id, 'location' => 'Family Section'],
            ['number' => 'F002', 'capacity' => 6, 'category_id' => $familyCategory->id, 'location' => 'Family Section'],
            ['number' => 'F003', 'capacity' => 8, 'category_id' => $familyCategory->id, 'location' => 'Family Section'],
            
            // VIP tables (VIP area)
            ['number' => 'V001', 'capacity' => 4, 'category_id' => $vipCategory->id, 'location' => 'VIP Area'],
            ['number' => 'V002', 'capacity' => 6, 'category_id' => $vipCategory->id, 'location' => 'VIP Area'],
            
            // Group tables (Event area)
            ['number' => 'G001', 'capacity' => 10, 'category_id' => $groupCategory->id, 'location' => 'Event Hall'],
            ['number' => 'G002', 'capacity' => 12, 'category_id' => $groupCategory->id, 'location' => 'Event Hall'],
            
            // Private rooms
            ['number' => 'P001', 'capacity' => 8, 'category_id' => $privateCategory->id, 'location' => 'Private Room 1'],
            ['number' => 'P002', 'capacity' => 6, 'category_id' => $privateCategory->id, 'location' => 'Private Room 2'],
        ];

        foreach ($tables as $index => $tableData) {
            Table::create([
                'name' => $tableData['number'],
                'capacity' => $tableData['capacity'],
                'status' => 'available',
                'qr_code' => null, // Will be auto-generated by model event
                'category_id' => $tableData['category_id'],
                'description' => "Table {$tableData['number']} - {$tableData['capacity']} seats",
                'location' => $tableData['location'],
                'service_type' => 'dine_in',
                // x_position and y_position will be auto-set by model boot method based on index
            ]);
        }

        $this->command->info("✅ Created " . count($tables) . " tables with categories");
    }
}
